### ISSUE TITLE
oppo的设备在安装的时候最后一个页面的安装没有找到并自动点过去

### ISSUE THREAD

**Issue by mashangfei** [SonicCloudOrg/sonic-plugin-android#4]
测试设备;oppo a9 （其他多款oppo的也一样）
测试步骤：安装好了sonic插件，保存了oppo安装密码，也开启了sonic服务
现象：安装的步骤会自动输入密码，自动点安装，直到最后一个需要点击安装的页面，没有识别到安装，需要手动点击。
![Screenshot_2021-12-17-15-59-15-85](https://user-images.githubusercontent.com/7725112/146510181-5c6a479b-2e16-4917-b84c-ec18a391606c.jpg)

**Comment by ZhouYixun** [comment]
该项目已不再维护~后续安装这一部分用ocr来处理，目前插件处理方式不够好
